//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 生成的包含文件。
// 供 RadarParse.rc 使用
//
#define IDOK2                           3
#define IDD_ABOUTBOX                    100
#define IDD_VIEW_MAIN                   101
#define IDR_POPUP_EDIT                  119
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define IDS_TOOLBAR_CUSTOMIZE           125
#define ID_VIEW_CUSTOMIZE               126
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAME_256               129
#define IDR_RadarParseTYPE             130
#define ID_WINDOW_MANAGER               131
#define ID_VIEW_SWATHLIST               133
#define ID_PROPERTIES                   135
#define ID_NEW_FOLDER                   143
#define ID_VIEW_OUTPUTWND               149
#define ID_VIEW_PROPERTIESWND           150
#define ID_SORTPROPERTIES               151
#define ID_PROPERTIES1                  152
#define ID_PROPERTIES2                  153
#define ID_EXPAND_ALL                   154
#define IDS_SWATH_VIEW                  155
#define IDS_CLASS_VIEW                  156
#define IDS_OUTPUT_WND                  157
#define IDS_PROPERTIES_WND              158
#define IDI_SWATH_VIEW                  161
#define IDI_SWATH_VIEW_HC               162
#define IDI_OUTPUT_WND                  165
#define IDI_OUTPUT_WND_HC               166
#define IDI_PROPERTIES_WND              167
#define IDI_PROPERTIES_WND_HC           168
#define IDR_EXPLORER                    169
#define IDB_EXPLORER_24                 170
#define IDR_POPUP_SORT                  173
#define IDR_POPUP_EXPLORER              174
#define IDB_SWATH_VIEW                  175
#define IDB_SWATH_VIEW_24               176
#define IDR_MENU_IMAGES                 179
#define IDB_MENU_IMAGES_24              180
#define ID_TOOLS_MACRO                  181
#define IDR_OUTPUT_POPUP                182
#define IDR_PROPERTIES                  183
#define IDB_PROPERTIES_HC               184
#define IDR_THEME_MENU                  200
#define ID_SET_STYLE                    201
#define IDS_BUILD_TAB                   300
#define IDS_DEBUG_TAB                   301
#define IDS_FIND_TAB                    302
#define IDS_EXPLORER                    305
#define IDS_EDIT_MENU                   306
#define IDR_HELP_MENU                   310
#define IDD_DIALOG_CARD                 311
#define IDD_VIEW_SETTING                313
#define IDD_VIEW_ASSISTANT              315
#define IDD_DIALOG_ZLEVEL               322
#define IDC_CHANNEL_DATA                1000
#define IDC_CHANNEL_TITLE               1001
#define ID_CARD_CREATE                  1002
#define IDC_CARD_NO                     1003
#define IDC_ACTIVITYCODE_DATA           1003
#define IDC_CARD_SIZE                   1004
#define IDC_ACTIVITYCODE_FILE           1004
#define IDC_EDIT_ACTIVITYCODE_FILE      1004
#define IDC_CARD_DEEP                   1005
#define IDC_CARD_B                      1006
#define IDC_CARD_HEIGHT                 1007
#define IDC_SLIDER_CONTRAST             1008
#define IDC_SLIDER_TIMEGAIN             1009
#define IDC_SLIDER_DEEP                 1010
#define IDC_SLIDER_DISTANCE             1011
#define IDC_SLIDER_ZLEVEL_MAIN_ONE      1011
#define IDC_STATIC_CONTRAST             1012
#define IDC_STATIC_TIMEGAIN             1013
#define IDC_STATIC_DEEP                 1014
#define IDC_STATIC_DISTANCE             1015
#define IDC_STATIC_ZLEVEL_ONE           1015
#define IDC_STATIC_ZLEVEL_MAIN_ONE      1015
#define IDC_STATIC_ZLEVEL_MAIN_TWO      1016
#define IDC_CARD_LEVEL                  1017
#define IDC_SLIDER_ZLEVEL_TWO           1017
#define IDC_SLIDER_ZLEVEL_MAIN_TWO      1017
#define IDC_CARD_TYPE                   1018
#define IDC_STATIC_ZLEVEL_LEFT_ONE      1018
#define IDC_CARD_L                      1019
#define IDC_SLIDER_ZLEVEL_LEFT_ONE      1019
#define IDC_CARD_N                      1020
#define IDC_STATIC_ZLEVEL_LEFT_TWO      1020
#define IDC_CARD_E                      1021
#define IDC_SLIDER_ZLEVEL_LEFT_TWO      1021
#define IDC_CARD_POSITION               1022
#define IDC_STATIC_ZLEVEL_LEFT_THREE    1022
#define IDC_CARD_TIME                   1023
#define IDC_SLIDER_ZLEVEL_LEFT_THREE    1023
#define IDC_CARD_FILE                   1024
#define IDC_STATIC_ZLEVEL_RIGHT_ONE     1024
#define IDC_CARD_BROWSE                 1025
#define IDC_SETTING_OPEN_LEFT           1025
#define IDC_ZLEVEL_SAVE                 1025
#define IDC_CODE_SAVE                   1025
#define IDC_CODE_DOWNLOAD               1025
#define IDC_CARD_PHOTO_FRONT            1026
#define IDC_SLIDER_ZLEVEL_RIGHT_ONE     1026
#define IDC_CARD_PHOTO_BACK             1027
#define IDC_STATIC_ZLEVEL_RIGHT_TWO     1027
#define IDC_CARD_PIC_SIDE1              1028
#define IDC_SLIDER_ZLEVEL_RIGHT_TWO     1028
#define IDC_CARD_PIC_SIDE2              1029
#define IDC_STATIC_ZLEVEL_RIGHT_THREE   1029
#define IDC_SLIDER_ZLEVEL_RIGHT_THREE   1030
#define IDC_CARD_PHOTO_FRONT2           1030
#define IDC_CARD_PHOTO_LEFT             1030
#define IDC_CARD_PHOTO_BACK2            1031
#define IDC_CARD_PHOTO_RIGHT            1031
#define IDC_CARD_PIC_SIDE3              1032
#define IDC_PICTURE_NAME_FRONT          1033
#define IDC_PICTURE_NAME_BACK           1034
#define IDC_LADAR_PICTURE1              1035
#define IDC_LADAR_PICTURE2              1036
#define IDC_SETTING_OPEN_RIGHT          1037
#define IDC_PICTURE_NAME_FRONT2         1037
#define IDC_PICTURE_NAME_LEFT           1037
#define IDC_PICTURE_NAME_BACK2          1038
#define IDC_PICTURE_NAME_RIGHT          1038
#define IDC_CARD_PIC_SIDE4              1039
#define IDC_LADAR_PICTURE3              1040
#define IDC_LADAR_PICTURE4              1041
#define IDC_EDIT1                       1056
#define IDC_CHECK1                      1063
#define IDC_SLIDER_DEEP_AUTO            1063
#define ID_FILE_MRU_SETTING             32771
#define ID_DISPLAY_IN_ONE               32772
#define ID_DISPLAY_IN_TWO               32773
#define ID_DISPLAY_LEFT_TWO             32777
#define ID_DISPLAY_LEFT_ONE             32778
#define ID_DISPLAY_LEFT_THREE           32779
#define ID_DISPLAY_RIGHT_ONE            32780
#define ID_DISPLAY_RIGHT_TWO            32781
#define ID_DISPLAY_RIGHT_THREE          32782
#define ID_OPEN_LEFT                    32785
#define ID_OPEN_RIGHT                   32786
#define ID_SETTING_ZLEVEL               32788
#define ID_REGISTER                     32790
#define ID_BUY                          32792
#define ID_ACTIVITY                     32793
#define ID_GETCODE                      32798
#define ID_OPEN_SWATH                   32800
#define ID_32801                        32801
#define ID_SETTING_PATH                 32802
#define ID_32803                        32803
#define ID_FILE_EXPORT                  32804
#define ID_INDICATOR_PROJECTPATH        59142
#define ID_INDICATOR_SWATH              59143
#define ID_INDICATOR_CHANNEL            59144

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        341
#define _APS_NEXT_COMMAND_VALUE         32805
#define _APS_NEXT_CONTROL_VALUE         1064
#define _APS_NEXT_SYMED_VALUE           310
#endif
#endif
